name: ci

on:
  push:
    branches:
      - 'wget'

#on: [push, pull_request]

jobs:
  build_job_a:
    # The host should always be linux
    runs-on: ubuntu-22.04
    name: Build on ubuntu20.04 (aarch64)
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Build artifact
        id: build
        with:
          #arch: aarch64
          #distro: ubuntu20.04
          arch: none
          distro: none
          base_image: --platform=linux/arm64/v8 ubuntu:20.04

          # Not required, but speeds up builds
          #githubToken: ${{ github.token }}

          # Create an artifacts directory
          setup: |
            mkdir -p "${PWD}/artifacts"

          # Mount the artifacts directory as /artifacts in the container
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"

          # Pass some environment variables to the container
          env: | # YAML, but pipe character is necessary
            artifact_name: wget

          # The shell to run commands with in the container
          shell: /bin/sh

          # Install some dependencies in the container. This speeds up builds if
          # you are also using githubToken. Any dependencies installed here will
          # be part of the container image that gets cached, so subsequent
          # builds don't have to re-install them. The image layer is cached
          # publicly in your project's package repository, so it is vital that
          # no secrets are present in the container state or logs.
          install: |
            apt-get update -q -y
            apt-get install git gcc g++ clang wget libgnutls28-dev libssl-dev -y

          # Produce a binary artifact and place it in the mounted volume
          run: |
            wget https://ftp.gnu.org/gnu/wget/wget-1.25.0.tar.gz
            tar xvzf wget-1.25.0.tar.gz
            cd wget-1.25.0
            ./configure --with-openssl
            make
            make install
            ls

      - name: Show the artifact
        # Items placed in /artifacts in the container will be in
        # ${PWD}/artifacts on the host..
        run: |
          ls -al "${PWD}/artifacts"
      - uses: actions/upload-artifact@v4
        with:
          name: build_a
          path: artifacts
  build_job_b:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: install dev package & deps
      run: |
        sudo apt-get update -q -y
        sudo apt-get install gcc g++ git clang wget libgnutls28-dev libssl-dev -y
    - name: build
      run: |
        wget https://ftp.gnu.org/gnu/wget/wget-1.25.0.tar.gz
        tar xvzf wget-1.25.0.tar.gz
        cd wget-1.25.0
        ./configure --with-openssl
        sudo make
        sudo make install
        ls
        

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with: 
        name: build_b
        path: artifacts
