name: Build fdk-aac Windows

on:
  push:
    branches:
      - 'win-aac'
  workflow_dispatch:

jobs:
  build-windows-fdk-aac:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]  # two architectures
    env:
      FDK_VERSION: master

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >
            base-devel
            mingw-w64-i686-toolchain
            mingw-w64-x86_64-toolchain
            mingw-w64-i686-autotools
            mingw-w64-x86_64-autotools
            mingw-w64-i686-pkg-config
            mingw-w64-x86_64-pkg-config
            git

      - name: Set MSYS2 environment
        shell: bash
        run: |
          if [ "${{ matrix.arch }}" == "x64" ]; then
            export MSYS_PREFIX="/c/msys64/mingw64"
          else
            export MSYS_PREFIX="/c/msys64/mingw32"
          fi
          echo "MSYS_PREFIX=$MSYS_PREFIX" >> $GITHUB_ENV
          export PATH="$MSYS_PREFIX/bin:$PATH"

      - name: Clone fdk-aac
        shell: bash
        run: |
          git clone https://github.com/mstorsjo/fdk-aac.git
          cd fdk-aac
          git checkout $FDK_VERSION

      - name: Build & install fdk-aac
        shell: bash
        run: |
          cd fdk-aac
          autoreconf -fiv
          PREFIX="$PWD/fdk-aac-prefix"
          ./configure --prefix="$PREFIX" --enable-static --enable-shared
          make -j$(nproc)
          make install

      - name: Zip fdk-aac
        shell: bash
        run: |
          cd fdk-aac
          mv fdk-aac-prefix ../fdk-build
          cd ..
          zip -r "fdk-aac-windows-${{ matrix.arch }}.zip" fdk-build

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: fdk-aac-windows-${{ matrix.arch }}
          path: fdk-aac-windows-${{ matrix.arch }}.zip
          retention-days: 1
